


ITERATIONS = 200_000
UPDATE_INTERVAL = 6
NUM_UPDATES_PER_IT = 1

LEARNING_RATE = 1e-4
BATCH_SIZE = 5
MAX_STEPS = 10
GAMMA = 0.9
POLYAK = 0.9
DISCOUNT_FACTOR = 0.95

TENSORBOARD_LOG = True
TB_LOG_PATH = r"C:\Users\tnf\Documents\NTNU\2024\WaterlooInternship\final_project\RL\runs\dqn"
SAVE_MODEL_PATH = r"C:\Users\tnf\Documents\NTNU\2024\WaterlooInternship\final_project\RL\models\saved_models"
SAVE_MODEL_EVERY_IT = 10_000

REPLAY_BUFFER_CAPACITY = 100_000


FINGERPRINT_LENGTH = 2040
FINGERPRINT_RADIUS = 3

ATOM_TYPES = ["C", "O", "N"]
INIT_MOL = None
ALLOW_REMOVAL = True
ALLOW_NO_MODFICATION = True
ALLOW_BOND_BETWEEN_RINGS = True
ALLOWED_RING_SIZES = [5,7]


